deployUrl=

eventuateMavenRepoUrl=https://snapshots.repositories.eventuate.io/repository
springBootVersion=4.1.1

eventuateCommonExamplesVersion=0.6.0.BUILD-SNAPSHOT

eventuatePluginsGradleVersion=0.15.0.BUILD-SNAPSHOT
junitVersion=6.0.3
junitPlatformLauncherVersion=6.0.3
eventuateTramSagasVersion=0.27.0.BUILD-SNAPSHOT

eventuateTramVersion=0.38.0.BUILD-SNAPSHOT
springwolfVersion=2.6.0

jacksonVersion=3.1.5
jacksonAnnotationsVersion=2.21
assertjVersion=3.27.7
restAssuredVersion=6.0.1
httpclient5Version=5.6.4

eventuateUtilVersion=0.20.0.BUILD-SNAPSHOT
versionProperty=eventuateTramSpringWolfSupportVersion

version=0.3.0-SNAPSHOT

