apply plugin: 'io.eventuate.tram.springwolf.validate-asyncapi'

dependencies {
    implementation project(":eventuate-tram-springwolf-support-core")
    implementation "org.springframework.boot:spring-boot-starter:$springBootVersion"
    implementation "org.apache.httpcomponents.client5:httpclient5:$httpclient5Version"
    compileOnly "io.eventuate.tram.core:eventuate-tram-events:$eventuateTramVersion"
    compileOnly "io.eventuate.tram.core:eventuate-tram-spring-events-starter:$eventuateTramVersion"

    testImplementation "io.eventuate.tram.core:eventuate-tram-events:$eventuateTramVersion"
    testImplementation "io.eventuate.tram.core:eventuate-tram-spring-events-starter:$eventuateTramVersion"
    testImplementation project(":eventuate-tram-springwolf-support-testing")
    testImplementation "org.springframework.boot:spring-boot-starter-webmvc-test:$springBootVersion"
    testImplementation "org.springframework.boot:spring-boot-starter-webmvc:$springBootVersion"
    testImplementation "io.rest-assured:rest-assured:$restAssuredVersion"
    testImplementation "io.eventuate.tram.core:eventuate-tram-spring-in-memory:$eventuateTramVersion"
    testImplementation "io.eventuate.util:eventuate-util-test:$eventuateUtilVersion"

    testRuntimeOnly "io.github.springwolf:springwolf-ui:$springwolfVersion"
}
tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
